{{- if .Values.storage.enabled }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pv.name }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClass }}
  hostPath:
    path: {{ .Values.storage.hostPath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc.name }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}

{{- end }}
